### PR TITLE
Preservation of forwarded environment

### PR DESCRIPTION
**Pull request by joshdk**

### CODE REVIEW

**Comment by joshdk** [comment]
This PR modifies two small pieces of behavior;

- The first is to not pass along empty environment variable values when they were not set in the Drone environment. This can cause very subtle bugs when programs expect variables to be set as sentinels: `if [[ -n FLAG ]]; then ...`

Behavior before:

Drone config | Drone env | Resulting host env
--- | --- | ---
`envs: [foo]` | `FOO=bar` | `FOO='bar'`
`envs: [foo]` | `FOO=` | `FOO=''`
`envs: [foo]` | `FOO` is unset | `FOO=''`

Behavior now:

Drone config | Drone env | Resulting host env
--- | --- | ---
`envs: [foo]` | `FOO=bar` | `FOO='bar'`
`envs: [foo]` | `FOO=` | `FOO=''`
`envs: [foo]` | `FOO` is unset | `FOO` is unset

- The second is to not longer remove all space characters from the Drone environment value. This can cause very subtle bugs as the original variable value is silently modified.

Behavior before:

Drone env | Resulting host env
--- | ---
`FOO='The quick brown fox jumps over the lazy dog'` | `FOO='Thequickbrownfoxjumpsoverthelazydog'`

Behavior now:

Drone env | Resulting host env
--- | ---
`FOO='The quick brown fox jumps over the lazy dog'` | `FOO='The quick brown fox jumps over the lazy dog'`

**Comment by joshdk** [comment]
Additionally, we can see that the modified test [originally fails](http://drone.wu-boy.com/appleboy/drone-ssh/155/7), with the environment being:

```
======ENV======
FOO='Valueforfoo'
BAR=''
BAZ=''
======END======
```

But then [subsequently passes](http://drone.wu-boy.com/appleboy/drone-ssh/156/7) with the modified code, and the environment being:

```
======ENV======
FOO='Value for foo'
BAR=''
======END======
```

Hope this helps, cheers!

**Comment by appleboy** [comment]
@joshdk We should escape the `'` symbal?

Foo=I'm appleboy => Foo='I\'m appleboy'

**Comment by joshdk** [comment]
@appleboy I did consider that, although it appeared there was(?) work being done in https://github.com/appleboy/drone-ssh/pull/108 to that effect. That being said, I was looking into writing a patch and came across the following which made me doubt that this is even possible.

To quote the [POSIX specification (section 2.2.2 on single-quotes)](http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html):

>2.2.2 Single-Quotes
>
>Enclosing characters in single-quotes ( '' ) shall preserve the literal value of each character within the single-quotes. A single-quote cannot occur within single-quotes.

If we want to do this the right way, reimplementing the POSIX rules for **double-quote** escaping might be our ticket.

Either way, I would advocate for putting it in a follow-up PR, as a new feature 😄

**Comment by appleboy** [comment]
@joshdk please help to resolve the conflicts since I merged #108 PR. Maybe make another PR for `double-quote escaping`.

**Comment by joshdk** [comment]
@appleboy rebased off of latest `master`.

**Pull request merged**
